### ISSUE TITLE
Prefill fields values depends on previous steps

### ISSUE THREAD

**Issue by 4n70w4** [armincms/wizard#2]
Hi!

I would like to implement such a scenario:
1) In first step user submit some data.
2) Validate data and request external API for external data.
3) Pre-fill second step with external data from API.
4) Save resource to DB.

How can I pass data to the second step?

**Comment by zareismail** [comment]
hey

> Hi!
> 
> I would like to implement such a scenario:
> 
> 1. In first step user submit some data.
> 2. Validate data and request external API for external data.
> 3. Pre-fill second step with external data from API.
> 4. Save resource to DB.
> 
> How can I pass data to the second step?

Hey! 
I think you should implement your custom form.

**Comment by 4n70w4** [comment]
@zareismail why then need an opportunity to group the fields in steps? If steps cannot be depends based on data from previous steps...

**Comment by zareismail** [comment]
> @zareismail why then need an opportunity to group the fields in steps? If steps cannot be depends based on data from previous steps...

This ability will be added later and now I'm working on it.
