### ISSUE TITLE
Bug: shows validation errors on second step after next button on first step

### ISSUE THREAD

**Issue by 4n70w4** [armincms/wizard#4]
![image](https://user-images.githubusercontent.com/38257723/72744930-9a324700-3bbf-11ea-837f-ea05c9027916.png)
![image](https://user-images.githubusercontent.com/38257723/72744957-a918f980-3bbf-11ea-94ab-4b682cacb00c.png)

**Comment by zareismail** [comment]
Hey!

I think that there is a field with the same attribute on the second step.
Can you display your fields to me?

**Comment by zareismail** [comment]
Hey!

I think that there is a field with the same attribute on the second step.
Can you display your fields to me?

**Comment by 4n70w4** [comment]
Yes, is a field with the same attribute on the second step.

And yes, I expect that in the second step in the field with the same attribute will be displayed the data filled from the field in the first step with the same attribute.

```php
            Step::make('Step One', [
                Text::make(__('INN'), 'inn')->hideFromIndex(),
            ]),

            Step::make('Step Two', [
                Text::make(__('INN'), 'inn')->readonly()->hideFromIndex(),
                Text::make(__('Title'), function () use($organization) {
                    return $organization ? $organization->title : null;
                })->readonly()->hideFromIndex(),

                Text::make(__('email'), 'email')->rules('required')->hideFromIndex(),
            ]),
```

**Comment by zareismail** [comment]
please upgrade to version 0.1.1
