### ISSUE TITLE
[Question] Is this project still being worked on?

### ISSUE THREAD

**Issue by ThaDaVos** [armincms/wizard#6]
I read a lot of issues which end with: 'Will be added in the next release' but as it seems there hasn't been any commits for multiple months, I've got to ask, is this project still being worked on or is it abandoned?

**Comment by zareismail** [comment]
Hi.
This project will be replaced with the new implementation soon.
Until that, you can use this

**Comment by christophrumpel** [comment]
Just tried the current version. Looks promising! 👍Can you already tell when the new version will be available? (approximately)
