### ISSUE TITLE
Error Nova 3 - Setp::make() should be compatible with Panel:make()

### ISSUE THREAD

**Issue by alalm3i** [armincms/wizard#7]
Hi, 
I tried to use this package with Nova 3 

I got the below error:

`Declaration of Armincms\Wizard\Step::make(string $name, $fields = Array) should be compatible with Laravel\Nova\Panel::make(...$arguments)`

**Comment by zareismail** [comment]
hi; thanks for reporting. please use [this package](https://github.com/zareismail/nova-wizard) instead of it
